// Auto-generated from the PBD reporting workbooks in docs/References/PBD/ (sheet "BI").
// Do not edit by hand — regenerate from the source workbooks. Malaysian PBD assessment:
// Tahap Penguasaan (mastery level) 1-6, where 6 is the highest. Keyed by class name.

export const PBD_BI_SUBJECT = "Bahasa Inggeris (English)";

export type PbdSkill = "listening" | "speaking" | "reading" | "writing";

export interface PbdBiRecord {
  name: string;
  gender: "L" | "P";
  listening: number;
  speaking: number;
  reading: number;
  writing: number;
  overall: number;
}

export interface PbdClassReport {
  teacher: string;
  records: PbdBiRecord[];
}

export const PBD_BI: Record<string, PbdClassReport> = {
  "2B": {
    teacher: "CHAN KOK WENG",
    records: [
      { name: "CHIN YU KAI", gender: "L", listening: 4, speaking: 4, reading: 3, writing: 3, overall: 3 },
      { name: "CHOO CHEN YUE", gender: "L", listening: 5, speaking: 4, reading: 4, writing: 5, overall: 5 },
      { name: "DOMINIC CHIN XIN YU", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "HERMAN LEE", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 3, overall: 4 },
      { name: "HO MING JIA", gender: "L", listening: 6, speaking: 6, reading: 5, writing: 5, overall: 6 },
      { name: "JAYDEN KHO YU ZHE", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "KEAY BOON GUAN", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 3, overall: 4 },
      { name: "LAI ZHAN LE", gender: "L", listening: 5, speaking: 4, reading: 5, writing: 4, overall: 5 },
      { name: "LOUIS TENG", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "LUCIUS LIN EE BIN", gender: "L", listening: 6, speaking: 5, reading: 5, writing: 5, overall: 5 },
      { name: "MCZWHELLER TAN EN HAO", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 4, overall: 4 },
      { name: "NG XUAN WEI", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "ONG ZI RUI", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 3, overall: 4 },
      { name: "POW YEE AN", gender: "L", listening: 6, speaking: 5, reading: 5, writing: 6, overall: 6 },
      { name: "RON LAI MIN HE", gender: "L", listening: 6, speaking: 6, reading: 6, writing: 5, overall: 6 },
      { name: "SEAH YOU JUN", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 3, overall: 4 },
      { name: "TAN QI HAN", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 3, overall: 4 },
      { name: "TEE SHI XUAN", gender: "L", listening: 5, speaking: 4, reading: 5, writing: 4, overall: 5 },
      { name: "TIU PO QIAN", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "TOH LE ZUN", gender: "L", listening: 2, speaking: 1, reading: 2, writing: 2, overall: 2 },
      { name: "WONG KE SHUN", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 3, overall: 4 },
      { name: "ABIGAIL LAU XIN YAN", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 3, overall: 4 },
      { name: "AGNES CHEW XUAN", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 3, overall: 4 },
      { name: "CHEE CHUI XIN", gender: "P", listening: 1, speaking: 1, reading: 1, writing: 1, overall: 1 },
      { name: "CHEONG JIN ROU", gender: "P", listening: 3, speaking: 2, reading: 2, writing: 2, overall: 2 },
      { name: "CHLOE LIM YU SIN", gender: "P", listening: 6, speaking: 5, reading: 6, writing: 6, overall: 6 },
      { name: "FONG RUO LING", gender: "P", listening: 3, speaking: 2, reading: 2, writing: 2, overall: 2 },
      { name: "JASLYN PEE JING SHUEN", gender: "P", listening: 5, speaking: 5, reading: 5, writing: 5, overall: 5 },
      { name: "LEE SHYAN QI", gender: "P", listening: 5, speaking: 5, reading: 4, writing: 5, overall: 5 },
      { name: "LIM PEI YEE", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 3, overall: 4 },
      { name: "LUI YUN XI", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 3, overall: 4 },
      { name: "SEE JING EN", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 4, overall: 4 },
      { name: "TAN PEI XUAN", gender: "P", listening: 6, speaking: 5, reading: 5, writing: 6, overall: 6 },
      { name: "TEYO SI TIAN", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "WONG JIN TIAN", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "WONG ZI QI", gender: "P", listening: 6, speaking: 5, reading: 6, writing: 6, overall: 6 },
      { name: "YAP YEE JYE", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
    ],
  },
  "2D": {
    teacher: "CHAN KOK WENG",
    records: [
      { name: "ADRIAN RAPHAEL ANAK JEFFERY", gender: "L", listening: 5, speaking: 4, reading: 4, writing: 5, overall: 5 },
      { name: "BRYAN LIN ZHI YING", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "CHAN JIA LE", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "CHEW WEN CHENG", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "EASON LEE YU ZE", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "HONG ZI HENG", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "JAYDEN NG JUN KAI", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 4, overall: 4 },
      { name: "KER MING HAO", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "LAY WEI MING", gender: "L", listening: 5, speaking: 4, reading: 4, writing: 5, overall: 5 },
      { name: "LOUIS WONG HAW TIRNG", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "NG MING LIANG", gender: "L", listening: 1, speaking: 1, reading: 1, writing: 1, overall: 1 },
      { name: "ONG KAI YOU", gender: "L", listening: 5, speaking: 4, reading: 4, writing: 5, overall: 5 },
      { name: "ONG ZI HAO", gender: "L", listening: 2, speaking: 2, reading: 2, writing: 2, overall: 2 },
      { name: "RAY TEE YUN LE", gender: "L", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "SIN SHAN HENG", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "TAN YAN JUN", gender: "L", listening: 5, speaking: 4, reading: 4, writing: 5, overall: 5 },
      { name: "TOH YI JIE", gender: "L", listening: 6, speaking: 5, reading: 5, writing: 6, overall: 6 },
      { name: "CHIN ENG QIN", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "DHARSHAYA LEE", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "GOH SIEW FEN ASHLEY", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "JOCELYN VOON ZHI NING", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "KOH YI XING", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "LEE XUE NA", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "LEW XIN YAO", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "LIM YU LING", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "OLIVIA CHIA XIN TONG", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "OLIVIA NYON LER XIN", gender: "P", listening: 6, speaking: 5, reading: 5, writing: 6, overall: 6 },
      { name: "OVIA PUSHPANATHAN", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "RUBY CHAN JIA EN", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "RUTH CHAN JIA XIN", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "SENG XIN LE", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "TAN YU TONG", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "THUM KAI EN", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "WONG WEN XING", gender: "P", listening: 4, speaking: 4, reading: 3, writing: 3, overall: 3 },
      { name: "YANZE LOW", gender: "P", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "YEE JING EN", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
    ],
  },
  "2F": {
    teacher: "CHAN KOK WENG",
    records: [
      { name: "ADRIAN KOH YU LE", gender: "L", listening: 5, speaking: 4, reading: 5, writing: 5, overall: 5 },
      { name: "AIDEN LOO ZI QUAN", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "ANSON CHU YU CHEN", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "CAYDEN DING HAU ZU", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "CHENG AARON", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "CHIEW MENG FONG", gender: "L", listening: 6, speaking: 5, reading: 6, writing: 5, overall: 6 },
      { name: "CHUAH JUN JIE", gender: "L", listening: 2, speaking: 2, reading: 2, writing: 2, overall: 2 },
      { name: "EASON TAN", gender: "L", listening: 5, speaking: 5, reading: 4, writing: 5, overall: 5 },
      { name: "JACKSON KONG WEI XIANG", gender: "L", listening: 3, speaking: 2, reading: 2, writing: 2, overall: 2 },
      { name: "JORDAN KOO YU HENG", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "KHOO YEE FONG", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "LEE XU HAN", gender: "L", listening: 5, speaking: 4, reading: 5, writing: 5, overall: 5 },
      { name: "MAVIN TAN YU XIAN", gender: "L", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "NEO JIA JUN", gender: "L", listening: 5, speaking: 5, reading: 4, writing: 5, overall: 5 },
      { name: "SOO JUN XING", gender: "L", listening: 6, speaking: 5, reading: 6, writing: 5, overall: 6 },
      { name: "WONG ZHI HAO", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "WU CHEN HE", gender: "L", listening: 6, speaking: 5, reading: 5, writing: 6, overall: 6 },
      { name: "AW YEE ZHEN", gender: "P", listening: 2, speaking: 2, reading: 2, writing: 2, overall: 2 },
      { name: "CHIN KAR KAY", gender: "P", listening: 5, speaking: 5, reading: 5, writing: 5, overall: 5 },
      { name: "DEEKSHIKA NAACHIYA A/P SAKTHISIVAM", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "DOREEN LUE ZHI QING", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "EE RU YING", gender: "P", listening: 2, speaking: 2, reading: 2, writing: 2, overall: 2 },
      { name: "GOH XIN TONG", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 3, overall: 4 },
      { name: "KANDYS TONG RUO EN", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "KOK YU HSUAN", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "LEE YU XI", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "LOH HUI EN", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "LOK JIA WEN", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "NG KE NING", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "PAN ZHI XIN", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "SI MIN CIN", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "TAN ZI TANG", gender: "P", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "TRISELLE CHONG CHEN XI", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "WONG YEE SHAN", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "YONG XIN YU", gender: "P", listening: 5, speaking: 4, reading: 5, writing: 5, overall: 5 },
      { name: "KYRA TAN XIN YU", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
    ],
  },
  "1B": {
    teacher: "CHAN KOK WENG",
    records: [
      { name: "ADAM TAN ZHI HONG", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 4, overall: 3 },
      { name: "AIDEN KUA JIA JUN", gender: "L", listening: 5, speaking: 4, reading: 4, writing: 5, overall: 5 },
      { name: "ALSON CHIN JIA HENG", gender: "L", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "CHAN ZHI YU", gender: "L", listening: 4, speaking: 4, reading: 4, writing: 3, overall: 4 },
      { name: "CHANG POH YUAN", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "CHONG KAH YUNN", gender: "L", listening: 5, speaking: 4, reading: 4, writing: 5, overall: 5 },
      { name: "CHONG MING XUAN", gender: "L", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "FOO YIK YEN", gender: "L", listening: 5, speaking: 5, reading: 5, writing: 5, overall: 5 },
      { name: "JACKSON KEE JUN KANG", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "KENSHIN PHANG JIAN XING", gender: "L", listening: 5, speaking: 5, reading: 5, writing: 5, overall: 5 },
      { name: "KHU FUL SHENG", gender: "L", listening: 4, speaking: 4, reading: 3, writing: 4, overall: 4 },
      { name: "LEUNG CHANG SENG", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "LILADHARISHAN A/L SUNTARESAN", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "LIN YOU JIAN", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 4, overall: 4 },
      { name: "ROY TAN CHEONG HONG", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "SOO KAH HO", gender: "L", listening: 5, speaking: 4, reading: 5, writing: 5, overall: 3 },
      { name: "SZEWITIAN WONG SHENG WEI", gender: "L", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "TEW YI SHENG", gender: "L", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "THAM YU ZHE", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "WONG YU YIN", gender: "L", listening: 4, speaking: 4, reading: 5, writing: 4, overall: 4 },
      { name: "ZAYN CHONG YU KAI", gender: "L", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "CAROL SOON KERK WEI", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "GLADYS LOH", gender: "P", listening: 5, speaking: 4, reading: 5, writing: 5, overall: 5 },
      { name: "HEDY NG YEE TONG", gender: "P", listening: 1, speaking: 1, reading: 1, writing: 2, overall: 1 },
      { name: "HO YU QI", gender: "P", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "JANICE LAM ZHI YAO", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 4 },
      { name: "KERK SHU YU", gender: "P", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "LEE VUI ZI", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "LIM EE HAN", gender: "P", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "LIM EE XI", gender: "P", listening: 2, speaking: 2, reading: 2, writing: 2, overall: 2 },
      { name: "LIM YAN XI", gender: "P", listening: 3, speaking: 2, reading: 2, writing: 2, overall: 2 },
      { name: "MIALATISSYA ANAK KATERINA", gender: "P", listening: 5, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "PANG YU ENN", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "TAN ROU XUAN", gender: "P", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "TAN ZI YUE", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 4, overall: 4 },
      { name: "YAN WAN NEE", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "YUNICE LEE YUNN XI", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
    ],
  },
  "1E": {
    teacher: "CHAN KOK WENG",
    records: [
      { name: "AHMAD UWAIS AISAR BIN FIRDAUS", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "CHARLES NGO JUN LE", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "CHOONG YU ZE", gender: "L", listening: 3, speaking: 3, reading: 3, writing: 2, overall: 3 },
      { name: "EDEN RAYYAN BIN MOHAMAD SYAFIQ CHAM", gender: "L", listening: 4, speaking: 4, reading: 3, writing: 3, overall: 4 },
      { name: "JORDAN TYE JUN TENG", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "LEONE TAN LI YANG", gender: "L", listening: 2, speaking: 2, reading: 2, writing: 2, overall: 2 },
      { name: "LOOI TONG XI", gender: "L", listening: 3, speaking: 2, reading: 2, writing: 2, overall: 2 },
      { name: "MARCUS ONG", gender: "L", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "MUHAMMAD AMEER NAIM BIN ABDUL AZIZ", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 4, overall: 4 },
      { name: "NEO KAI XUAN", gender: "L", listening: 5, speaking: 5, reading: 5, writing: 5, overall: 5 },
      { name: "RAQIB NOR IMAN BIN KHAIRY", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "SEOW ZE YU", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "TAN RO HE", gender: "L", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "TEAH LI YANG", gender: "L", listening: 5, speaking: 4, reading: 5, writing: 5, overall: 5 },
      { name: "TIO KAI WEN", gender: "L", listening: 5, speaking: 4, reading: 5, writing: 5, overall: 5 },
      { name: "WONG TAK XIN", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 4, overall: 4 },
      { name: "WONG YI JUN", gender: "L", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "YUEN JIA RUI", gender: "L", listening: 3, speaking: 2, reading: 2, writing: 3, overall: 2 },
      { name: "ALVINA CHUA", gender: "P", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "CHAN AI RA", gender: "P", listening: 5, speaking: 4, reading: 5, writing: 5, overall: 5 },
      { name: "CHEW ZHI SHAN", gender: "P", listening: 5, speaking: 4, reading: 5, writing: 5, overall: 5 },
      { name: "JAYCE SOON CHEN XI", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 4, overall: 4 },
      { name: "KAYLA LEE QIAN LOK", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 4, overall: 4 },
      { name: "KEE YA LI", gender: "P", listening: 5, speaking: 4, reading: 5, writing: 4, overall: 5 },
      { name: "KOH EN QI", gender: "P", listening: 5, speaking: 4, reading: 5, writing: 5, overall: 5 },
      { name: "LEE JIA YUE", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "LEE YU XUAN", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "NG WEE EN", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "NUHA ARFA IBTIHAJ BINTI MOHD FAIZAL", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "QUINTA NGOI YAN XING", gender: "P", listening: 5, speaking: 5, reading: 5, writing: 5, overall: 5 },
      { name: "TAN YU NING", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "VIIEN TEE", gender: "P", listening: 3, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "WONG XING YU", gender: "P", listening: 4, speaking: 3, reading: 3, writing: 3, overall: 3 },
      { name: "YAP XIN NING", gender: "P", listening: 4, speaking: 4, reading: 4, writing: 4, overall: 4 },
      { name: "YAP ZI MOON", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
      { name: "YUNA BANG PEI RAN", gender: "P", listening: 4, speaking: 3, reading: 4, writing: 4, overall: 4 },
    ],
  },
};
