// Class pet system. A pet is a visual reward layer over the behaviour points the
// app already tracks (see lib/store.tsx getPupilExp): a pupil's positive-behaviour
// points ARE the pet's experience (EXP). Pets only grow — negative marks never
// shrink them — which keeps the mechanic kind for young pupils and matches the
// "raising" idea. Nothing here changes scoring; it only maps existing points onto
// a level, an evolution stage, and a sprite.
//
// Art: sprites live in public/pets/<species>/<stage>.png, generated by
// scripts/generate-pets.mjs (original AI art — the reference app's images are
// copyright-registered and are NOT used). Until a sprite exists the card falls
// back to an emoji, so the feature works before any art is generated.

export interface PetSpecies {
  id: string; // stable key stored on the pupil's pet.species
  label: string; // shown in the picker
  emoji: string; // fallback face + picker glyph
  blurb: string; // one-line flavour text
}

// Eight starter species. Add more freely — ids are the source of truth, so a new
// species only needs its four sprites dropped into public/pets/<id>/.
export const PET_SPECIES: PetSpecies[] = [
  { id: "dragon", label: "Dragon", emoji: "🐉", blurb: "Brave and a little fiery." },
  { id: "fox", label: "Fox", emoji: "🦊", blurb: "Clever and quick-thinking." },
  { id: "cat", label: "Cat", emoji: "🐱", blurb: "Curious and cosy." },
  { id: "owl", label: "Owl", emoji: "🦉", blurb: "Wise and watchful." },
  { id: "penguin", label: "Penguin", emoji: "🐧", blurb: "Friendly and full of waddle." },
  { id: "rabbit", label: "Rabbit", emoji: "🐰", blurb: "Gentle and full of hops." },
  { id: "dino", label: "Dino", emoji: "🦕", blurb: "Big-hearted and bold." },
  { id: "unicorn", label: "Unicorn", emoji: "🦄", blurb: "Magical and kind." },
  { id: "dog", label: "Dog", emoji: "🐶", blurb: "Loyal and always cheerful." },
  { id: "panda", label: "Panda", emoji: "🐼", blurb: "Calm and full of snacks." },
  { id: "koala", label: "Koala", emoji: "🐨", blurb: "Sleepy and very cuddly." },
  { id: "pig", label: "Pig", emoji: "🐷", blurb: "Happy and a little cheeky." },
  { id: "monkey", label: "Monkey", emoji: "🐵", blurb: "Playful and full of mischief." },
  { id: "tiger", label: "Tiger", emoji: "🐯", blurb: "Brave with a big heart." },
  { id: "mouse", label: "Mouse", emoji: "🐭", blurb: "Tiny, clever and quick." },
];

export const DEFAULT_SPECIES = PET_SPECIES[0].id;

export const speciesById = (id: string): PetSpecies =>
  PET_SPECIES.find((s) => s.id === id) ??
  PET_SPECIES.find((s) => s.id === DEFAULT_SPECIES)!;

// ---- Evolution stages -------------------------------------------------------
// Every pet moves through the same four stages; the level bands below decide
// which stage a pet is in. Each stage has its own sprite per species.

export interface PetStage {
  id: string; // sprite filename (public/pets/<species>/<id>.png) + stored key
  label: string;
  minLevel: number; // first level (inclusive) at which this stage begins
}

export const PET_STAGES: PetStage[] = [
  { id: "egg", label: "Egg", minLevel: 1 },
  { id: "baby", label: "Baby", minLevel: 2 },
  { id: "teen", label: "Teen", minLevel: 4 },
  { id: "adult", label: "Adult", minLevel: 7 },
];

/** Position of a stage in the evolution order (egg 0 → adult 3); -1 if unknown. */
export function stageIndexOf(stageId?: string): number {
  return stageId ? PET_STAGES.findIndex((s) => s.id === stageId) : -1;
}

// The stage for a given level (highest band whose minLevel is reached).
export function stageForLevel(level: number): PetStage {
  let stage = PET_STAGES[0];
  for (const s of PET_STAGES) {
    if (level >= s.minLevel) stage = s;
  }
  return stage;
}

// ---- Level curve ------------------------------------------------------------
// EXP needed to advance FROM `level` to `level + 1`. Starts at 10 and grows by 5
// each level, so early wins come fast and later levels feel earned:
//   L1→L2 = 10, L2→L3 = 15, L3→L4 = 20, …
export function expToNext(level: number): number {
  return 10 + (Math.max(1, level) - 1) * 5;
}

export interface LevelInfo {
  level: number; // current level (>= 1)
  intoLevel: number; // EXP earned into the current level
  needForNext: number; // EXP required to finish the current level
  progress: number; // 0..1 fraction of the current level completed
  totalExp: number; // the raw EXP passed in
}

// Resolve a raw EXP total into level + progress. Walks the curve from level 1;
// the per-level cost is tiny so this loop is cheap even for large totals.
export function levelFromExp(totalExp: number): LevelInfo {
  const exp = Math.max(0, Math.floor(totalExp));
  let level = 1;
  let remaining = exp;
  // Safety cap so a pathological total can never spin forever.
  while (level < 999 && remaining >= expToNext(level)) {
    remaining -= expToNext(level);
    level += 1;
  }
  const needForNext = expToNext(level);
  return {
    level,
    intoLevel: remaining,
    needForNext,
    progress: needForNext > 0 ? remaining / needForNext : 0,
    totalExp: exp,
  };
}

// ---- Sprites & fallbacks ----------------------------------------------------

// Path to a species/stage sprite. Bump PET_ART_VERSION when regenerating art so
// browsers don't serve a stale cached PNG under the same stable filename.
export const PET_ART_VERSION = "2";

export function spriteFor(speciesId: string, stageId: string): string {
  return `/pets/${speciesId}/${stageId}.png?v=${PET_ART_VERSION}`;
}

// Emoji shown until a sprite loads (or when art hasn't been generated yet). The
// egg stage is a universal 🥚 for every species — it "hatches" into the species
// face from the baby stage on, which reads as growth without needing art.
export function petEmoji(speciesId: string, stageId: string): string {
  if (stageId === "egg") return "🥚";
  return speciesById(speciesId).emoji;
}
